import "./globals.css";
import { Inter } from "next/font/google";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import ProductSection from "@/components/ProductSection";
import Footer from "@/components/Footer";
import useTextDirection from "@/components/useTextDirection";
import { useTranslations } from "next-intl";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const t = useTranslations("Index");
  const locale = useLocale();
  const direction = useTextDirection(locale);
  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <ClerkProvider>
      <html lang={locale} dir={direction}>
        <body className={inter.className}>
          {" "}
          <Header />
          {children}
          <ProductSection productsName={t("productsName")} />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
